### PR TITLE
Explicitly check for post vars

### PR DESCRIPTION
**Pull request by maxfenton**
To prevent a PHP notice, explicitly check for $_POST['post_status'] before checking its value.

### CODE REVIEW

**Comment by ddksr** [comment]
Hi,

sorry for not responding earlier. When does this even happen? With images?

**Comment by maxfenton** [comment]
Hi @ddksr — before I patched it, it was happening when I opened the home page of a site in development that has `define('WP_DEBUG', true);` in the wp-config.php

**Comment by ddksr** [comment]
Hm, I always have this setting and never notice it ... but nevertheless, it's a good practice. I would like to merge it but could you please remove the version bump because we will do it later?

**Comment by ddksr** [comment]
@maxfenton sorry, i see you already did

**Comment by maxfenton** [comment]
Thank you @ddksr. (I'm new to pull requests and had included that in my own copy just to prevent it from reverting in the Wordpress Dashboard.)

**Pull request closed without merging**
